### ISSUE TITLE
Include DESCRIPTION.rst in pypi packaging

### ISSUE THREAD

**Issue by claydugo** [sparkfun/DE2120_Py#2]
```
Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
  Created temporary directory: /tmp/pip-pip-egg-info-vbijttbw
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/staged-recipes/build_artifacts/de2120-barcode-scanner_1675119583057/work/setup.py", line 44, in <module>
      with io.open(path.join(here, "DESCRIPTION.rst"), encoding="utf-8") as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/staged-recipes/build_artifacts/de2120-barcode-scanner_1675119583057/work/DESCRIPTION.rst'
```

**Comment by hmaarrfk** [comment]
To bring a little context, this issue came up when trying to use the source distribution (the tar.gz) file to create a conda-package for your software on conda-forge.

While the `DISTRIBUTION.rst` file is in the repository, it isn't being copied in to the "python source distribution" at "creation time".

This makes it impossible to rebuild the package from the source distribution file.

Adding it to the MANIFEST.in file at the top level will ensure that it gets included

See:
* https://packaging.python.org/en/latest/tutorials/packaging-projects/#including-other-files
* https://packaging.python.org/en/latest/guides/using-manifest-in/
